language: php
addons:
  code_climate:
    repo_token: 272e5dabb61913265213c3851e8541428cacae0a10aff19c17c30743a100b2fd
before_script: composer install --dev
after_script:
  - vendor/bin/test-reporter
